services:
  booking-db:
    image: postgres:15
    container_name: booking-db
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5437:5432"   # use unique port, 5433 is taken by hotel-db
    volumes:
      - booking_db_data:/var/lib/postgresql/data
    networks:
      - booking-network

  booking-redis:
    image: redis:7-alpine
    container_name: booking-redis
    ports:
      - "6380:6379"   # use unique port, 6379 is taken by hotel-redis
    networks:
      - booking-network

volumes:
  booking_db_data:

networks:
  booking-network:
    driver: bridge