services:
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"   # 5433=hotel-db, 5435=wallet-db, 5436=user-db
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - user-network

  user-redis:
    image: redis:7-alpine
    container_name: user-redis
    ports:
      - "6381:6379"
    networks:
      - user-network

volumes:
  user_db_data:

networks:
  user-network:
    driver: bridge